#!/usr/bin/env bash
# Generate secrets.h next to the sketch, from .env.test. Never prints the
# password. If you would rather not run this, write secrets.h by hand instead --
# the README shows what goes in it.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env.test"

[ -f "$ENV_FILE" ] || { echo "missing $ENV_FILE (copy .env.test.example)" >&2; exit 1; }
set -a; . "$ENV_FILE"; set +a
: "${WIFI_SSID:?WIFI_SSID not set in .env.test}"
: "${WIFI_PASS:?WIFI_PASS not set in .env.test}"

# escape backslash and double quote for C string literals
esc() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

out="$ROOT/secrets.h"
cat > "$out" <<EOF
// GENERATED by scripts/gen_secrets.sh from .env.test -- DO NOT COMMIT
#pragma once
#define WIFI_SSID "$(esc "$WIFI_SSID")"
#define WIFI_PASS "$(esc "$WIFI_PASS")"
EOF
chmod 600 "$out"

echo "wrote secrets.h (ssid=$WIFI_SSID, password hidden)"
